sudo: false

language: go
go:
  - "1.10"

before_install:
  - make setup

script:
  - make SEMVER=${TRAVIS_TAG} deploy

notifications:
  email: false

branches:
  only:
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH}
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tags: true
